### ISSUE TITLE
?file

### ISSUE THREAD

**Issue by schloerke** [hadley/helpr#2] opened 2010-05-21 05:15 UTC
traceback:
  4: highlight(reconstruct(untag(rd$examples)))
  5: parser(text = examples)

Line 55 has a problem

The file states:

  # remove trailing commas. Suppose
  writeLines(c("450, 390, 467, 654,  30, 542, 334, 432, 421,",
  "357, 497, 493, 550, 549, 467, 575, 578, 342,",
  "446, 547, 534, 495, 979, 479"), "data2_")
  ## Not run
  % cat data2
  450, 390, 467, 654,  30, 542, 334, 432, 421,
  357, 497, 493, 550, 549, 467, 575, 578, 342,
  446, 547, 534, 495, 979, 479
  ## 

with the problem occurring with line:
  % cat data2

The 'writeLines' statement does not exist in the original examples.

**Comment by hadley** [comment] 2010-05-22 15:04
Fixed in 78319ffbe313c0ad3e5c0b7d0f956138dec0760b - the problem is the that code in the \dontrun section wasn't valid R code.

**Closed as completed** 2010-05-22 15:04 UTC
